menu:
  home: /
  archive: /archives
  category: /categories
  tag: /tags
  about: /about

toc: true
mathjax: true
highlightjs: true

style:
  hljs: "js/highlight.min.js"
  light:
    site: "css/light.css"
    code: "css/github.min.css"
  dark:
    site: "css/dark.css"
    code: "css/github-dark.min.css"
