# 注意需要保证对应页具有相同的名字
menu:
  home: /
  archive: /archive
  categories: /categories
  tagcloud: /tagcloud
  about: /about

toc: true
mathjax: true

# 网站主题
style:
  # 根据highlight.js网站推荐
  code:
    light: css/github.min.css
    dark: css/github-dark.min.css
  site:
    light: css/light/light.css
    dark: css/dark/dark.css

link:
  github:
    icon: ''
    url: 'HuzerOVO'

# Gitalk 插件设置
gitalk:
  # CDN
  css: https://unpkg.com/gitalk/dist/gitalk.css
  js: https://unpkg.com/gitalk/dist/gitalk.min.js
  md5js: https://cdn.bootcdn.net/ajax/libs/blueimp-md5/2.19.0/js/md5.min.js
  # Gitalk配置
  enable: true
  clientID: 8430fc1311285afb9029
  clientSecret: 6d9f1ff1d6db0df95fd537a3f3b2c686d35d641a
  repo: huzerovo.github.io
  owner: HuzerOVO
  admin: 
    - HuzerOVO
  distractionFreeMode: false

# jQurey CDN
jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js

# highlight.js 配置
hljs:
  enable: true
  # highlight.js CDN
  js: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js

# bootstrap CDN
bootstrap: https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css

