# 首页可以有个与顶栏中不同的名字
index: 首页

# 注意需要保证对应页具有相同的名字
menu:
  home:
    title: 首页
    link: /
  archive:
    title: 归档
    link: /archive
  categories:
    title: 分类
    link: /categories
  tagcloud:
    title: 标签云
    link: /tagcloud
  about:
    title: 关于我
    link: /about

# 邮箱
email: 'example@example.com'

# 网站搜索功能
search:
  enable: true
  link: /search

# 是否开启目录，这是个全局选项
toc: true

# 数学公式渲染
katex:
  enable: true
  css: https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  js:
    - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js 
    - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js

# 网站主题
style:
  # 根据highlight.js网站推荐
  code:
    light: 'css/github.min.css'
    dark: 'css/github-dark.min.css'
  site:
    light: 'css/light/light.css'
    dark: 'css/dark/dark.css'

# Gitalk 插件设置
# CDN
gitalk_source:
  css: 'https://cdn.bootcdn.net/ajax/libs/gitalk/1.8.0/gitalk.css'
  js: 'https://cdn.bootcdn.net/ajax/libs/gitalk/1.8.0/gitalk.js'
  md5js: 'https://cdn.bootcdn.net/ajax/libs/blueimp-md5/2.19.0/js/md5.min.js'

# Gitalk配置
gitalk:
  enable: true
  clientID: 'Github Application Client ID'
  clientSecret: 'Github Application Client Secret'
  repo: 'Github repo'
  owner: 'Github repo owner'
  admin: 
    - 'Github repo owner and collaborators'
  distractionFreeMode: false

# jQurey CDN
jquery: 'https://cdn.bootcdn.net/ajax/libs/jquery/3.6.4/jquery.min.js'

# Fancybox
fancybox:
  enable: true
  css: 'https://cdn.bootcdn.net/ajax/libs/fancyapps-ui/5.0.16/fancybox/fancybox.min.css'
  js: 'https://cdn.bootcdn.net/ajax/libs/fancyapps-ui/5.0.16/fancybox/fancybox.umd.min.js'

# highlight.js 配置
hljs:
  enable: true
  # highlight.js CDN
  js: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js'

# bootstrap CDN
bootstrap: 'https://cdn.bootcdn.net/ajax/libs/bootstrap-icons/1.10.4/font/bootstrap-icons.min.css'

# Font awesome 用于支持bootstrap中缺少外链的图标
fontawesome: 'https://cdn.bootcdn.net/ajax/libs/font-awesome/6.4.0/js/all.min.js'

# 外链
links:
  github:
    title: 'Github'
    class: 'bi bi-github'
    url: 'https://github.com'
# bilibili:
#   title: 'BiliBili'
#   class: 'fa-brands fa-bilibili'
#   url: 'https://www.bilibili.com'

# 订阅
rss:
  enable: true
  path: atom.xml
