# 首页可以有个与顶栏中不同的名字
index: 首页

# 注意需要保证对应页具有相同的名字
menu:
  home:
    title: 首页
    link: /
  archive:
    title: 归档
    link: /archive
  categories:
    title: 分类
    link: /categories
  tagcloud:
    title: 标签云
    link: /tagcloud
  about:
    title: 关于我
    link: /about

# 网站搜索功能
search:
  enable: true
  link: /search

# 是否开启目录，这是个全局选项
toc: true

# 数学公式渲染
mathjax: true

# 网站主题
style:
  # 根据highlight.js网站推荐
  code:
    light: 'css/github.min.css'
    dark: 'css/github-dark.min.css'
  site:
    light: 'css/light/light.css'
    dark: 'css/dark/dark.css'

# Gitalk 插件设置
# CDN
gitalk_source:
  css: 'https://cdn.bootcdn.net/ajax/libs/gitalk/1.8.0/gitalk.css'
  js: 'https://cdn.bootcdn.net/ajax/libs/gitalk/1.8.0/gitalk.js'
  md5js: 'https://cdn.bootcdn.net/ajax/libs/blueimp-md5/2.19.0/js/md5.min.js'

# Gitalk配置
gitalk:
  enable: true
  clientID: 8430fc1311285afb9029
  clientSecret: 6d9f1ff1d6db0df95fd537a3f3b2c686d35d641a
  repo: 'huzerovo.github.io'
  owner: HuzerOVO
  admin: 
    - HuzerOVO
  distractionFreeMode: false

# jQurey CDN
jquery: 'https://cdn.bootcdn.net/ajax/libs/jquery/3.6.4/jquery.min.js'

# Fancybox
fancybox:
  enable: true
  css: 'https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css'
  js: 'https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js'

# highlight.js 配置
hljs:
  enable: true
  # highlight.js CDN
  js: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js'

# bootstrap CDN
bootstrap: 'https://cdn.bootcdn.net/ajax/libs/bootstrap-icons/1.10.4/font/bootstrap-icons.min.css'

# 外链
# 尚未实现...
link:
  github:
    icon: ''
    url: ''
